### ISSUE TITLE
working with opencv4

### ISSUE THREAD

**Issue by thenasfarce** [vivekhsridhar/tracktor#11]
not a bug, but just a note. installing opencv by using `conda install -c menpo opencv3` causes a downgrade to python 2.7. however, i found it's possible to still run tracktor using open cv4 and retaining python 3.x by using `pip install opencv-python`, and then modifying tracktor.py lines 67/68 to accommodate the return tuple on cv2.findCountours(). have found no other bugs after this change, as i think the img variable wasn't used within the function in the first place
`
contours, hierarchy = cv2.findContours(thresh.copy(), cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
#img = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
`

**Comment by Rhamidi47** [comment]
Hi, 
I failed to load all the videos for the tests. Although I have followed the recommendations well :

sys.exit('Video file cannot be read! Please check input_vidpath to ensure it is correctly pointing to the video file').

Then, I applied the corrections proposed by "thenasfarce". I installed a recent version of python (>3) and corrected the script. 

Same.

Then, I also thought it was a codec problem, so I installed pip install ffmpeg-python...

Same

Tracktor can not find the videos on my computer.

Any solutions please ?

**Comment by vivekhsridhar** [comment]
Dear Rhamidi,

As the error suggests, this is not due to opencv or python versions. This error is because you haven't specified path to the video file correctly. Specifying the correct path should fix this error.

Cheers!
Vivek
