### ISSUE TITLE
Unbound local error

### ISSUE THREAD

**Issue by dhanya-bharath** [vivekhsridhar/tracktor#14]
Hi,

I am getting the following error message when I run the tracking code in cell 3 for the first example video.

`UnboundLocalError                         Traceback (most recent call last)
<ipython-input-5-18464b0433bb> in <module>
     25         frame = cv2.resize(frame, None, fx = scaling, fy = scaling, interpolation = cv2.INTER_LINEAR)
     26         thresh = tr.colour_to_thresh(frame, block_size, offset)
---> 27         final, contours, meas_last, meas_now = tr.detect_and_draw_contours(frame, thresh, meas_last, meas_now, min_area, max_area)
     28         row_ind, col_ind = tr.hungarian_algorithm(meas_last, meas_now)
     29         final, meas_now, df = tr.reorder_and_draw(final, colours, n_inds, col_ind, meas_now, df, mot, this)

~\Downloads\tracktor-master\examples\tracktor.py in detect_and_draw_contours(frame, thresh, meas_last, meas_now, min_area, max_area)
     69     else:
     70         contours, hierarchy = cv2.findContours(thresh.copy(), cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
---> 71     img = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
     72 
     73     final = frame.copy()

UnboundLocalError: local variable 'img' referenced before assignment`

Would be grateful for any help regarding this!

Best,
Dhanya

**Comment by vivekhsridhar** [comment]
Dear Dhanya,

This is a result of different versions of opencv. Unfortunately it's hard for me to debug this at my end but I've made some changes to the code. Could you redownload the tracktor.py file from the examples folder and tell me if it works now?

CHeers!
Vivek

**Comment by dhanya-bharath** [comment]
Hi Vivek,

It works beautifully now! Thank you so much :)

Best,
Dhanya
