### ISSUE TITLE
Live tracking from camera stream(s) and interface with other programs

### ISSUE THREAD

**Issue by melop** [vivekhsridhar/tracktor#21]
Hi, when I was doing my PhD I used the Biobserve Viewer software for real time tracking and controlling video stimuli. How hard would it be to make traktor work on live video streams and allow zone settings, such that when an animal enters a zone it broadcasts a command (say with UDP), so that another program (say video server, pump server) can react?
I am trying to set up my own lab now but the commercial solutions are really expensive.
Thanks!

**Comment by vivekhsridhar** [comment]
@melop, I haven't really played around much with this. But OpenCV has a ready possibility to use webcam videos. So it should in theory be possible. The question then becomes what framerate the recording is at and whether tracktor is able to keep up with tracking 'n individuals' within that time in the concerned recording pc.
Hope that helps and sorry for the delayed response
