### ISSUE TITLE
error when running the example vedio

### ISSUE THREAD

**Issue by Ethanyang504** [vivekhsridhar/tracktor#23]
during installation, everything looks fine, when I tried to run the tracktor using the example videos. the 1st and 2nd cell are good. however, when it goes to the 3rd cell, it keeps gives me an error below.
I tried the 3a, 3b and 3c, the error is the same. could you please give me some suggestions what is this error about?

AttributeError                            Traceback (most recent call last)
<ipython-input-3-e174a8ed5c1a> in <module>
      7 # make sure the frame size matches size of array 'final'
      8 fourcc = cv2.VideoWriter_fourcc(*codec)
----> 9 output_framesize = (int(cap.read()[1].shape[1]*scaling),int(cap.read()[1].shape[0]*scaling))
     10 out = cv2.VideoWriter(filename = output_vidpath, fourcc = fourcc, fps = 30.0, frameSize = output_framesize, isColor = True)
     11 

AttributeError: 'NoneType' object has no attribute 'shape

**Comment by saulobritto** [comment]
Hi,
I'm trying to use Tracktor and i got this error a few days ago. The problem was the name of the video or the video path. Please check them, including the /.
Check too the file type you are choosing (+ video + '.mp4'), if it is not mp4, change it in the code.

I hope it will solve your problem.

**Comment by vivekhsridhar** [comment]
Thanks for solving the issue @saulobritto
