### ISSUE TITLE
Import tracktor error - No module named 'tracktor'

### ISSUE THREAD

**Issue by emelynetjw** [vivekhsridhar/tracktor#24]
Hi,

I am trying to work through the example file, but I got this error msg when I ran cell 1:

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-5-25ec684a8d04> in <module>
      1 import numpy as np
      2 import pandas as pd
----> 3 import tracktor as tr
      4 import cv2
      5 import sys

ModuleNotFoundError: No module named 'tracktor'

Is there a tracktor library / package and how to install it?

Thank you.

**Comment by vivekhsridhar** [comment]
All the functions for tracktor are in the tracktor.py file. This file has to remain in the same folder as your example

Cheers!
Vivek
------------------------------------
Vivek Hari Sridhar
website: www.vhsridhar.wordpress.com <http://www.vhsridhar.wordpress.com/>

**Comment by emelynetjw** [comment]
I see. Thank you!
