### ISSUE TITLE
ValueError: XA must be a 2-dimensional array.

### ISSUE THREAD

**Issue by siva-athi** [vivekhsridhar/tracktor#26]
Hello Vivek!

All the provided example videos work with the code. When I use the video I recorded, this is the error I am getting. Could you please help me with this?

ValueError                                Traceback (most recent call last)
Cell In[3], line 36
     34 thresh = tr.colour_to_thresh(frame, block_size, offset)
     35 final, contours, meas_last, meas_now = tr.detect_and_draw_contours(frame, thresh, meas_last, meas_now, min_area, max_area)
---> 36 row_ind, col_ind = tr.hungarian_algorithm(meas_last, meas_now)
     37 final, meas_now, df = tr.reorder_and_draw(final, colours, n_inds, col_ind, meas_now, df, mot, this)
     39 # Create output dataframe

File D:\locomotion python\tracktor-master\tracktor-master\examples\tracktor.py:169, in hungarian_algorithm(meas_last, meas_now)
    167 meas_last = list(meas_last)
    168 meas_now = list(meas_now)
--> 169 cost = cdist(meas_last, meas_now)
    170 row_ind, col_ind = linear_sum_assignment(cost)
    171 return row_ind, col_ind

File D:\locomotion python\miniconda\envs\NOS_locomotion\Lib\site-packages\scipy\spatial\distance.py:2982, in cdist(XA, XB, metric, out, **kwargs)
   2979 sB = XB.shape
   2981 if len(s) != 2:
-> 2982     raise ValueError('XA must be a 2-dimensional array.')
   2983 if len(sB) != 2:
   2984     raise ValueError('XB must be a 2-dimensional array.')

ValueError: XA must be a 2-dimensional array.

**Comment by vivekhsridhar** [comment]
Hi,

The reason for this error is that your thresholding parameters aren't right. The hungarian algorithm expects to detect blobs so it can match identities in successive frame. In your case, the thresholding parameters (block_size and offset) are such that suitable objects are not generated. I recommend silencing line 35 onwards and visualising the thresh image on the cv2.imshow(...). This should help you optimise these parameters.

Cheers!
Vivek
