### ISSUE TITLE
list function attribution error when running examples

### ISSUE THREAD

**Issue by cvargas4** [vivekhsridhar/tracktor#4]
Hi, I really hope this isn't as simple as a problem as it might look to be. 
I tried running cell3 in jupyter using all of the example videos. On each one I got this error:

`AttributeError                            Traceback (most recent call last)
<ipython-input-3-1982db789d30> in <module>()
     29         frame_red = np.concatenate((redch, redch, redch), axis=2)
     30         thresh = tr.colour_to_thresh(frame_red, block_size, offset)
---> 31         final, contours, meas_last, meas_now = tr.detect_and_draw_contours(frame, thresh, meas_last, meas_now, min_area, max_area)
     32         row_ind, col_ind = tr.hungarian_algorithm(meas_last, meas_now)
     33         final, meas_now, df = tr.reorder_and_draw(final, colours, n_inds, col_ind, meas_now, df, mot, this)

/Users/cesarvargas/Documents/GitHub/tracktor/tracktor-master/examples/tracktor.pyc in detect_and_draw_contours(frame, thresh, meas_last, meas_now, min_area, max_area)
     71 
     72     i = 0
---> 73     meas_last = meas_now.copy()
     74     del meas_now[:]
     75     while i < len(contours):

AttributeError: 'list' object has no attribute 'copy'`

I double checked that all the required packages were installed and that I was running the kernel. The only thing I had changed in cell 2 for these was the file paths as needed.

Has this happened other times, or is there a particular issues I'm missing that I didn't check for?

Thanks in advance!

**Comment by cvargas4** [comment]
Sorry about this. I tried reinstalling everything on a new environment and the problem was solved! No idea where the issue lied.

Looking forward to getting to test out and use this!

**Comment by vivekhsridhar** [comment]
Sorry about the delayed response. I was on holiday the past month. Glad you got it working. :)

Vivek
