### ISSUE TITLE
cannot import cv2 after installing opencv

### ISSUE THREAD

**Issue by AlessandroCresci90** [vivekhsridhar/tracktor#5]
Hi! I have been trying to correctly install opencv so that when I run 'python import cv2' I wouldn't get any error.

I installed opencv, from within my environment, running: 'conda install -c menpo opencv3' 

The installation was OK and I did not get any error message. However, when I run 'python import cv2' I get the following error: 'python: can't open file 'import': [Errno 2] No such file or directory'

I tried many things to fix this.. even installing opencv with an exe file, and then copy cv2.pyd into the lib/site-packages folder. But nothing.

Could you help me with this?

Thank you in advance!
Alessandro

**Comment by Cemal67** [comment]
I need same help in my installment.
