### ISSUE TITLE
Unable to open video 

### ISSUE THREAD

**Issue by MaximePolicarpo** [vivekhsridhar/tracktor#7]
Hello,
I am trying to install tracktor on my computer (ubuntu). I have successfully install everything but i have an error when trying to run the example "3a Fish_fast-start..."

When running the third cell of the example with jupyter notebook ("The cell below runs the tracking code"), i got the following message : 

"An exception has occurred, use %tb to see the full traceback.
SystemExit: Video file cannot be read! Please check input_vidpath to ensure it is correctly pointing to the video file"

I tried to change the path of the video in the second cell , trying various things as:
input_vidpath = '/../videos/' + video + '.mp4'
input_vidpath = '/home/gambusia/Bureau/Tracking_Behavioral_Tests/tracktor-master/videos/' + video + '.mp4'

But i always get the same error. I also tried to launch the video from python in my conda env directly from the videos folder:

>python
>import cv2
>codec = 'DIVX'
>cv2.VideoCapture("fish_video.mp4")

And here i got this error : 

"Unable to stop the stream: Inappropriate ioctl for device
<VideoCapture 0x7f0e6d1d1670>"

Do you have any idea where the problem come from and how i could resolve it ?

Thanks,

Maxime Policarpo

**Comment by vivekhsridhar** [comment]
Dear Maxime,
 I'm sorry I can't be very helpful with this since I've never encountered the error myself. A quick google search suggests this happens because your OpenCV isn't linking to ffmpeg correctly. I'm not sure if this helps but check these links out (maybe you already have):
https://stackoverflow.com/questions/41200201/opencv-unable-to-stop-the-stream-inappropriate-ioctl-for-device
https://github.com/bytedeco/javacv/issues/1087

**Comment by MaximePolicarpo** [comment]
Thanks for your answer, i will try to fix that !

Ps : It is very rare to have detailed installation steps and complete guide as you have written, so thank you for that effort !

Maxime

________________________________
De : Vivek Hari Sridhar <notifications@github.com>
Envoyé : jeudi 17 janvier 2019 09:56
À : vivekhsridhar/tracktor
Cc : MaximePolicarpo; Author
Objet : Re: [vivekhsridhar/tracktor] Unable to open video (#7)


Dear Maxime,
I'm sorry I can't be very helpful with this since I've never encountered the error myself. A quick google search suggests this happens because your OpenCV isn't linking to ffmpeg correctly. I'm not sure if this helps but check these links out (maybe you already have):
https://stackoverflow.com/questions/41200201/opencv-unable-to-stop-the-stream-inappropriate-ioctl-for-device
bytedeco/javacv#1087<https://github.com/bytedeco/javacv/issues/1087>
